name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Run Jest tests
      run: npm test

    - name: Run Prettier
      run: npx prettier --check "**/*.{js,jsx,json,md}"

    - name: Run ESLint
      run: npx eslint .

    - name: Report status
      if: failure()
      uses: Mattwwilson34/ultistats.com@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: |
          There were some issues with your code. Please fix them and try again.
